In [62]:
import numpy as np
from keras.models import Sequential
from keras.layers import Dense, TimeDistributed, Activation, LSTM
from keras.utils import np_utils

import os

#brew install graphviz
#pip3 install graphviz
#pip3 install pydot-ng
from keras.utils.vis_utils import plot_model

#sample text
sample = "hihello"

In [63]:
char_set = list(set(sample)) #중복제거
char_dic = {w: i for i, w in enumerate(char_set)} #index붙여 dic으로


In [64]:
#test data??
x_str = sample[:-1]
y_str = sample[1:]
print(x_str)
print(y_str)

data_dim = len(char_set)
timesteps = len(y_str)
num_classes = len(char_set)

x=[char_dic[c] for c in x_str]
y=[char_dic[c] for c in y_str] # char to index
print(len(char_set))
print(x)
print(y)

hihell
ihello
5
[0, 1, 0, 4, 3, 3]
[1, 0, 4, 3, 3, 2]


In [65]:
#one-hot encoding
x=np_utils.to_categorical(x,num_classes=num_classes) # 0 1 0 4 3 3 자리
print(x)
#reshape X to be [samples, time steps, features]
x=np.reshape(x,(-1, len(y),data_dim))
print(x.shape)
print(x)
#one-hot encoding
y=np_utils.to_categorical(y, num_classes=num_classes)
#print(y)
#time steps
y=np.reshape(x,(-1,len(y),data_dim))
print(y.shape)



[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 1. 0.]]
(1, 6, 5)
[[[1. 0. 0. 0. 0.]
  [0. 1. 0. 0. 0.]
  [1. 0. 0. 0. 0.]
  [0. 0. 0. 0. 1.]
  [0. 0. 0. 1. 0.]
  [0. 0. 0. 1. 0.]]]
(1, 6, 5)


In [68]:
model = Sequential()
model.add(LSTM(num_classes, input_shape=(timesteps, data_dim), return_sequences= True))
model.add(TimeDistributed(Dense(num_classes)))
model.add(Activation('softmax'))
model.summary()
#Store model graph in png
#(Error occurs on in python interactive shell)
#plot_model(model, to_file=os.path.basename(__file__)+'.png', show_shapes=True)

model.compile(loss='categorical_crossentropy',optimizer='rmsprop', metrics=['accuracy'])
model.fit(x,y,epochs=1)

Model: "sequential_6"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
lstm_3 (LSTM)                (None, 6, 5)              220       
_________________________________________________________________
time_distributed_3 (TimeDist (None, 6, 5)              30        
_________________________________________________________________
activation_3 (Activation)    (None, 6, 5)              0         
Total params: 250
Trainable params: 250
Non-trainable params: 0
_________________________________________________________________
Epoch 1/1
1/1 [==============================] - 0s 473ms/step - loss: 1.4759 - accuracy: 0.6667
