In [5]:
import numpy as np
from keras.models import Sequential
from keras.layers import Dense, TimeDistributed, Activation, LSTM
from keras.utils import np_utils

import os

#brew install graphviz
#pip3 install graphviz
#pip3 install pydot-ng
from keras.utils.vis_utils import plot_model

#sample text
sample = "hihello"

char_set = list(set(sample)) #id->char['i','l','e','o','h']
char_dic = {w: i for i, w in enumerate(char_set)}

x_str = sample[:-1]
y_str = sample[1:]

data_dim = len(char_set)
timesteps = len(y_str)
num_classes = len(char_set)

print(x_str, y_str)

x=[char_dic[c] for c in x_str]
y=[char_dic[c] for c in y_str] #char to index

#one-hot encoding
x=np_utils.to_categorical(x,num_classes=num_classes)
#reshape X to be [samples, time steps, features]
x=np.reshape(x,(-1,len(y),data_dim))
print(x.shape)

#one-hot encoding
y=np_utils.to_categorical(y, num_classes=num_classes)
#time steps
y=np.reshape(x,(-1,len(y),data_dim))
print(y.shape)

model = Sequential()
model.add(LSTM(num_classes, input_shape=(
    timesteps, data_dim), return_sequences= True))
model.add(TimeDistributed(Dense(num_classes)))
model.add(Activation('softmax'))
model.summary()
#Store model graph in png
#(Error occurs on in python interactive shell)
#plot_model(model, to_file=os.path.basename(__file__)+'.png', show_shapes=True)

model.compile(loss='categorical_crossentropy', optimizer='rmsprop', metrics=['accuracy'])
model.fit(x,y,epochs=1)

predictions=model.predict(x,verbose=0)
for i, prediction in enumerate(predictions):
    print(prediction)
    x_index=np.argmax(x[i],axis=1)
    x_str = [char_set[j] for j in x_index]
    print(x_index, ''.join(x_str))
    
    index=np.argmax(prediction, axis=1)
    result=[char_set[j] for j in index]
    print(index, ''.join(result))

hihell ihello
(1, 6, 5)
(1, 6, 5)
Model: "sequential_3"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
lstm_3 (LSTM)                (None, 6, 5)              220       
_________________________________________________________________
time_distributed_3 (TimeDist (None, 6, 5)              30        
_________________________________________________________________
activation_3 (Activation)    (None, 6, 5)              0         
Total params: 250
Trainable params: 250
Non-trainable params: 0
_________________________________________________________________
Epoch 1/1
1/1 [==============================] - 0s 179ms/step - loss: 1.6104 - accuracy: 0.5000
[[0.20577633 0.20303729 0.18814479 0.18846147 0.21458007]
 [0.19222407 0.19876842 0.18972239 0.19369404 0.22559106]
 [0.20274873 0.20255873 0.18335216 0.18101017 0.23033026]
 [0.20865816 0.21210122 0.18328156 0.18247536 0.21348366]
 [0.21231094 0.20684768

In [6]:
print(char_set)
print(data_dim)
print(x_str)
print(y_str)

['l', 'i', 'o', 'h', 'e']
5
['h', 'i', 'h', 'e', 'l', 'l']
ihello
